### PR TITLE
Patches

### PR DESCRIPTION
**Pull request by eriede**
This PR

* Adds exponent format parsing and tokenizer tests for "NUMBER_FLOAT" tokens
* Adds the ability to set custom malloc functions (to accommodate memory pools, for instance)

Thanks!

### CODE REVIEW

**Comment by lassik** [comment]
Thanks for the patches! Let's hope @rsms can merge these upstream.

Looks good to me, the only nit is that having both `lalloc` and `lrealloc` seems redundant. In standard C, `realloc(NULL, 1234)` is the same as `malloc(1234)`. Can `lalloc` be left out?

**Comment by lassik** [comment]
You could even make `lrealloc(ptr, 0)` an alias for `free(ptr)` since there's no need to allocate zero bytes, and in standard C it's undefined behavior. `lrealloc(NULL, 0)` can be a no-op.

**Comment by lassik** [comment]
In other words:

```C
static void *lrealloc(void *ign, void *p, size_t size) {
    (void)ign; // unused
    if (size) return realloc(p, size);
    free(p);
    return NULL;
}
```

**Comment by eriede** [comment]
I've never seen it done that way before... not that I'm opposed.   Most libs that I have seen provide three separate callbacks, prepending a void * for a context.  It does create a single function to hold in the json context, instead of the three that we would need otherwise, but the downside is that it is a little less fluent.  

If you prefer it that way, I can have another PR shortly. 

Yes, it would be nice if the original implementer was still maintaining.  At least we can have all the changes in one place .

**Comment by lassik** [comment]
Thanks for updaging the PR! LGTM.

Interesting that libraries take all three since `realloc(NULL, n)` in particular is well known, and fluent in that it does the right thing when you initialize a buffer pointer to `NULL`. IMHO less API surface is better, but if @rsms prefers more functions we can change it.

**Pull request merged**
